name: notebook2
dependencies:
- python=3.7
- requests
- flask
- pip
- pip:
  - kubernetes
  - Flask_Sockets
  - libsass
<<<<<<< HEAD
  - authlib
=======
>>>>>>> 3f82dc9e64d95e5e25d1494c4f722c24c496ff6a
